### ISSUE TITLE
Change format of articles/contents.yml

### ISSUE THREAD

**Issue by ordinary-dev** [ordinary-dev/linux-blog#5]
Something like that will be better:
```yaml
'1':
  title: Where am I?
  date: 2021-06-11
```
